# exception

Задание проверил. 

Все верно
